# Generated by Django 3.2.9 on 2021-12-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
