# Generated by Django 3.2.9 on 2021-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('request', models.TextField()),
            ],
        ),
    ]
